spring:
  application:
    name: rabbitmq-thread-manager
  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      concurrency: 1
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
        max-interval: 10000
    template:
      reply-timeout: 5000
      retry:
        enabled: true
        initial-interval: 5000
        max-attempts: 3
        max-interval: 15000

server:
  port: 8080

security:
  basic:
    enabled: false
  management:
    security:
      enabled: false
